# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "test.Person" do
    optional :first_name, :string, 1
    optional :last_name, :string, 2
    optional :age, :int32, 3
  end
  add_message "test.PersonAny" do
    repeated :persons, :message, 1, "google.protobuf.Any"
  end
  add_message "test.PersonArray" do
    repeated :persons, :message, 1, "test.Person"
  end
end

module Test
  Person = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Person").msgclass
  PersonAny = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.PersonAny").msgclass
  PersonArray = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.PersonArray").msgclass
end
